{% set name = "incqueryserver-api-python-client" %}
{% set version = "0.27.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/incqueryserver-api-python-client-{{ version }}.tar.gz
  sha256: d48e46e599e4b91ccb6ddde8addb21ff45ef2d4ac7592fbc6198a803f8182c88

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - certifi
    - python >={{ python_min }}
    - python-dateutil
    - six >=1.10
    - urllib3 >=1.15

test:
  imports:
    - iqs_client
    - iqs_client.api
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://incquery.io
  license: Apache-2.0
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: IncQuery Servers Web API

extra:
  recipe-maintainers:
    - FuzesiMate
    - pappist
    - abelhegedus
    - ujhelyiz
    - bergmanngabor
