{% set name = "incqueryserver-api-python-client" %}
{% set version = "0.21.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/incqueryserver-api-python-client-{{ version }}.tar.gz
  sha256: e7a51eac5dc4d63c5c7f815c3c2db6932d2d3e82e22a5c9e3c3a6d9f3e069474

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python =2.7|>=3.4
  run:
    - certifi
    - python =2.7|>=3.4
    - python-dateutil
    - six >=1.10
    - urllib3 >=1.15

test:
  imports:
    - iqs_client
    - iqs_client.api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://incquery.io
  license: Apache-2.0
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: IncQuery Servers Web API

extra:
  recipe-maintainers:
    - FuzesiMate
    - pappist
    - abelhegedus
    - ujhelyiz
    - bergmanngabor
