{% set name = "incqueryserver-api-python-client" %}
{% set version = "0.26.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/incqueryserver-api-python-client-{{ version }}.tar.gz
  sha256: dc09d59401cc3e4f92eedc3b46a030f6bfc83da7087de13447a11b0e9a91745c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - certifi
    - python >=2.7
    - python-dateutil
    - six >=1.10
    - urllib3 >=1.15

test:
  imports:
    - iqs_client
    - iqs_client.api
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://incquery.io
  license: Apache-2.0
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: IncQuery Servers Web API

extra:
  recipe-maintainers:
    - FuzesiMate
    - pappist
    - abelhegedus
    - ujhelyiz
    - bergmanngabor
